### ISSUE TITLE
Installation of oitei fails because of malformed version requirement

### ISSUE THREAD

**Issue by kthth** [UB-Mannheim/escriptorium#2]
oitei version 1.0.0 has a malformed version requirement, as noted in https://github.com/OpenITI/oitei/pull/9. So maybe the version should be changed to 1.1.1

**Comment by stweil** [comment]
Thank you for the reminder. I created a merge request to fix this:
https://gitlab.com/scripta/escriptorium/-/merge_requests/344

 Please write future issues for the primary repository at GitLab. This here is only a clone.
