### ISSUE TITLE
Is the scikit version correct?

### ISSUE THREAD

**Issue by kthth** [UB-Mannheim/escriptorium#3]
When running the latest version (c8ddbbcb) I get this message:

     scikit-learn version 1.2.2 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.

Is this ok?

**Comment by stweil** [comment]
This is "normal". I see it since I am working with eScriptorium. And I also find it confusing and would be happy to get it fixed.

**Comment by stweil** [comment]
The latest kraken release has a fix which suppresses those warnings. See https://github.com/mittagessen/kraken/issues/536 for details.
